name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:      
    runs-on: [ self-hosted, "${{ matrix.os }}", "${{ matrix.architecture }}" ]
    strategy:
      fail-fast: false
      matrix:
        os: ["Linux", "Windows", "macOS"]
        architecture: ["ARM64"]
        
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: cmake -S . -B build -G Ninja
    - name: Build 
      run: cmake --build build -j
